### ISSUE TITLE
Name for Library

### ISSUE THREAD

**Issue by cfahlgren1** [cfahlgren1/observers#1]
Find an open PyPy name. Bonus if there is a domain name that is free for it as well.

**Comment by ParagEkbote** [comment]
A couple of suggestions:

1) Observo-Sleek name

2)LightObsy- PyPy Styling of Observo

Since 2) is unclaimed, you could get at a low price.
http://lightobsy.com/

Let me know what you think @cfahlgren1

**Comment by davidberenstein1957** [comment]
@ParagEkbote I already claimed observers :)

**Comment by ParagEkbote** [comment]
@davidberenstein1957 That's great! Excited to see how the library develops. Please let me know if you have any good first issues to contribute towards.

**Comment by davidberenstein1957** [comment]
@ParagEkbote we created some good first issue :)
