### ISSUE TITLE
loop of observation

### ISSUE THREAD

**Issue by malv-c** [cfahlgren1/observers#27]
synthetic intelligence does not exist yet (or some are cached)...5
anyway if an IA observe itself it should be enable to modify itself and create new one...
i don't know  python and thanks to make me know about pdm...
will you make observer a real framework to help synthetic intelligence to exist...
don't be afraid humans are good for dreaming...
no real intelligence will want to loose it.

**Comment by davidberenstein1957** [comment]
Hi @malv-c, closing this to keep the focus on specific issues and feature requests. Feel free to open something new based on a specific request.

**Comment by malv-c** [comment]
hi all
i can understand my short post is a big thing
but anyway a why not or a no never should not be too long to think...

Le mar. 26 nov. 2024 à 13:40, David Berenstein ***@***.***> a
écrit :
