### ISSUE TITLE
[FEAT] Add methods to go from `sqllite`/`duckdb` to `Datasets`/`Argilla`

### ISSUE THREAD

**Issue by davidberenstein1957** [cfahlgren1/observers#32]
@cfahlgren1 I thought this might be useful WDYT?

```python
from observers.stores DatasetsStore, DuckdbStore, sync_stores

existing_store = DuckdbStore()
new_store = DatasetsStore()
sync_stores(from=existing_store, to=new_store)
```

**Comment by cfahlgren1** [comment]
Can you expand a little more? I'm not sure I fully understand

**Comment by cfahlgren1** [comment]
Maybe it could instead be apart of https://github.com/cfahlgren1/observers/issues/12 and Datasets can use an existing local duckdb file? 🤔

**Comment by davidberenstein1957** [comment]
Closing in favor of #12
